image:
  file: .gitpod.Dockerfile

tasks:
  - init: bundle install
    command: >
      rake db:create 
      rake --trace db:migrate
      rake --trace db:seed
      rake import:all
      mkdir tmp/pids
