# buildspec.yml
version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the zip file...
      - ./build.sh
      - mv deploy/policeboard.zip policeboard.zip

artifacts:
  files: policeboard.zip