branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
  nginx-config:
    environment: dev-env
global:
  application_name: policeboard
  branch: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
