branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: policeboard
  branch: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
