branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: policeboard
  branch: null
  default_platform: 64bit Amazon Linux 2 v3.0.3 running Ruby 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
