# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11b2d246690132926cb5d6d735a04637a1b09d9186483ad170b7d92f3a509f974d30998730e4178339680b5cac33a091f8fa798c2e69510b9c854b391cbd0aa

test:
  secret_key_base: ae3291d193e7504ee7e18be4f5ad0131bfd8f15d3282c3e9776e10b829f0e6d36eed6844af2810cff11b5fce2427ec711c80aa6071f85d40d4f3290043366a74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
