menubar: false,
toolbar1: styleselect | undo redo | bold italic | bullist numlist | sub sup | indent outdent | justifyleft justifycenter justifyright | link unlink anchor | table | imagemanager | documentmanager | media sidebar | charmap | hr | removeformat code
  - table
  - fullscreen
plugins:
  - image
  - link
