menubar: false,
toolbar1: styleselect | undo redo | bold italic | bullist numlist | sub sup | indent outdent | justifyleft justifycenter justifyright | link unlink anchor | table | image  media | charmap | hr | removeformat code
plugins:
  - image
  - link
  - anchor
  - charmap
  - hr
  - lists
  - media
  - table
